# Generated by Django 5.1.3 on 2025-01-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticle",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
