# Generated by Django 5.1.3 on 2025-01-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogarticle_views"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogArticle",
            new_name="Article",
        ),
    ]
