# Generated by Django 5.1.3 on 2025-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_blogarticle_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["created_at"], "verbose_name": "публикация", "verbose_name_plural": "публикации"},
        ),
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
